# Generated by Django 3.0 on 2020-01-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
